name: Unit Test
on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Load Docker cache
        id: cache-docker
        uses: actions/cache@v3
        with:
          path: .docker-cache
          key: ${{ runner.os }}-docker-cache-${{ hashFiles('.devcontainer/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-cache-

      - name: Prepare Docker cache
        run: |
          mkdir -p .docker-cache

      - name: Load cached Docker image
        run: |
          if [ -f .docker-cache/docker-cache.tar ]; then
            docker load -i .docker-cache/docker-cache.tar
            echo "Loaded cached image"
          else
            echo "No cached image found"
          fi

      - name: Build Docker image
        run: |
          docker build -t ctmd-dev-container -f .devcontainer/Dockerfile .
          docker save ctmd-dev-container -o .docker-cache/docker-cache.tar

      - name: Save Docker cache
        uses: actions/cache@v3
        with:
          path: .docker-cache
          key: ${{ runner.os }}-docker-cache-${{ hashFiles('.devcontainer/Dockerfile') }}

      - name: Run container
        run: |
          docker run -d --name ctmd-container -v ${{ github.workspace }}:/workspaces/ctmd ctmd-dev-container tail -f /dev/null

      - name: Restore Bazel cache
        uses: actions/cache@v3
        with:
          path: /root/.cache/bazel
          key: ${{ runner.os }}-bazel-cache

      - name: Run tests in container
        run: |
          docker exec ctmd-container bash -c "cd /workspaces/ctmd && bazel test //..."

      - name: Save Bazel cache
        uses: actions/cache@v3
        with:
          path: /root/.cache/bazel
          key: ${{ runner.os }}-bazel-cache

      - name: Cleanup
        run: |
          docker stop ctmd-container
          docker rm ctmd-container
